### ISSUE TITLE
pass scikit-learn estimator test

### ISSUE THREAD

**Issue by pavanramkumar** [glm-tools/pyglmnet#157]
every `scikit-learn` compatible estimator should have certain methods. 
http://scikit-learn.org/stable/developers/contributing.html#rolling-your-own-estimator

one of them is `set_params()`. 

We need a PR that
- implements `set_params()`
- modifies tests to include the `scikit-learn` estimator test: http://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.check_estimator.html

**Comment by pavanramkumar** [comment]
@themantalope is working on this

**Comment by themantalope** [comment]
I implemented the `set_params` function but I'm still having issues when running `sklearn.utils.estimator_checks.check_estimator` function.

Example output:
```python 
>>> import pyglmnet
>>> from sklearn.utils.estimator_checks import check_estimator
>>> check_estimator(pyglmnet.GLM)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/antalek/anaconda/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 239, in check_estimator
    check_parameters_default_constructible(name, Estimator)
  File "/Users/antalek/anaconda/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 1461, in check_parameters_default_constructible
    assert_array_equal(param_value, init_param.default)
  File "/Users/antalek/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 811, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/antalek/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 737, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 100.0%)
 x: array([ 0.5     ,  0.323739,  0.209614,  0.135721,  0.087876,  0.056898,
        0.03684 ,  0.023853,  0.015445,  0.01    ])
 y: array(None, dtype=object)
```

From the sklearn documentation, it's failing at this part of the `check_estimator` function:

```python
for init_param in init_params:
            assert_not_equal(init_param.default, init_param.empty,
                             "parameter %s for %s has no default value"
                             % (init_param.name, type(estimator).__name__))
            assert_in(type(init_param.default),
                      [str, int, float, bool, tuple, type(None),
                       np.float64, types.FunctionType, Memory])
            if init_param.name not in params.keys():
                # deprecated parameter, not in get_params
                assert_true(init_param.default is None)
                continue

            param_value = params[init_param.name]
            if isinstance(param_value, np.ndarray):
                assert_array_equal(param_value, init_param.default)
            else:
                assert_equal(param_value, init_param.default)
```

**Comment by pavanramkumar** [comment]
I see, yes, it seems like `check_estimator` doesn't like us changing `reg_lambda` within `__init__`. 

One simple fix could be that we set the default as: 
`np.logspace(np.log(0.5), np.log(0.01), 10, base=np.exp(1))`
and then deal with list vs. array checks inside `fit()`.

Can you try if this works?

**Comment by themantalope** [comment]
I had tried that before and got a very opaque error:

```python
======================================================================
ERROR: test_pyglmnet.test_check_estimator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antalek/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/antalek/Documents/ProgrammingProjects/PythonProjects/pyglmnet/tests/test_pyglmnet.py", line 298, in test_check_estimator
    check_estimator(GLM)
  File "/Users/antalek/anaconda/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 239, in check_estimator
    check_parameters_default_constructible(name, Estimator)
  File "/Users/antalek/anaconda/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 1450, in check_parameters_default_constructible
    % (init_param.name, type(estimator).__name__))
  File "/Users/antalek/anaconda/lib/python2.7/unittest/case.py", line 519, in assertNotEqual
    if not first != second:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by pavanramkumar** [comment]
So you tried changing: https://github.com/pavanramkumar/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L130 to `reg_lambda = np.logspace(np.log(0.5), np.log(0.01), 10, base=np.exp(1))`

and https://github.com/pavanramkumar/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L136 to `self.reg_lambda = reg_lambda` ?

**Comment by themantalope** [comment]
Yes, that is correct.

**Comment by pavanramkumar** [comment]
Can you give me push access to your fork (add me as collaborator)? I'm a bit busy until Thursday but I can take a look afterwards.

**Comment by pavanramkumar** [comment]
@themantalope I'm close to passing the scikit-learn estimator test. 
- I assigned `reg_lambda` as a scalar in the `__init__()` method
- I made `set_params()` return `self`.

There are no mystery bugs any more, but `fit()` complains that `reg_lambda` is a scalar and therefore not iterable.

It seems that the long term fix is clear: we need two classes `GLM()` and `GLMCV()`. 
- `GLM()` should accept only scalar `reg_lambda`. 
- `GLMCV()` should return the coefs along the reg. path. that are estimated with warm restarts.

Writing this carefully can take a week or so. I'd vote to move it to `version 0.2`. We should follow the parameterization here as closely as possible: http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html

**Comment by themantalope** [comment]
@pavanramkumar hmm, I tried those things on my branch but I was still getting weird errors. I can take another look.

I agree, `GLMCV` should be its own class, and leaving it for now is OK. I will start working on it for the 0.2 release.

**Comment by pavanramkumar** [comment]
@themantalope thanks, i pushed some of my changes to your fork. i made a separate branch called `estimator_test`. you can choose to merge those changes if they help.

**Comment by themantalope** [comment]
Ok, mine is also working without any ambiguous errors, but it's still having problems with the expectation that `reg_lambda` should be some kind of iterable. 

From what I can tell, the `check_estimator` function does not like when the default value for an object's property is some kind of iterable type, which is right now directly at odds with how the `GLM` object is designed. Perhaps it would be best to turn the `GLM` object into a list of `GLM` objects? Or perhaps return an estimator object for each combination of parameters of the `GLM` object?

**Comment by pavanramkumar** [comment]
Hey @themantalope yes, it's simply that the way `GLM()` is written, `fit()` iterates through all values in `reg_lambda` which it expects to be a list. `check_estimator` wants all parameters to be scalar because otherwise it's not compatible with `GridSearchCV`.

I have a good sense of exactly what to do next to write `GLM()` and `GLMCV()` but need to spend the limited time ahead on tackling issues related to `version 0.1` milestone, due Oct 31. Perhaps it's best if we can sit together one day after this deadline and code it together? I'll keep you posted.

**Comment by themantalope** [comment]
Yeah, that's a good idea.

**Comment by jasmainak** [comment]
I was actually looking if there was a WIP code somewhere so that I could help but it seems that all the WIP code is private. @themantalope could you make a PR if you already have some code? It's always a good idea to make a PR early ...

**Comment by jasmainak** [comment]
Closing issue since we agreed that we will conform to scikit-learn standards only in spirit and getting the estimator checks to pass is a wormhole
